CREATE DATABASE IF NOT EXISTS blogdb;
USE blogdb;
CREATE TABLE IF NOT EXISTS authores
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(101) NOT NULL UNIQUE,
    imagen VARCHAR(200) DEFAULT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    categoria VARCHAR(125),
    actor_id INT,
    FOREIGN KEY (actor_id) REFERENCES authores(id) ON DELETE SET NULL
);